temperature: <T> # K
duration: <DURATION> #fs
n_inner: 5 # compiled innner steps
sampling_rate: 1 # dump interval
dt: 0.5 # fs time step
dr_threshold: 0.5 # Neighborlist skin

sim_dir: md
initial_structure: <INITIAL_STRUCTURE>
