n_epochs: <NUMBER OF EPOCHS>
seed: 1

data:
  model_path: models/
  model_name: gmnn


  # Use either data_path for a single dataset file
  # or the lines below to specify separate files
  data_path: <PATH>
  #train_data_path: <PATH>
  #val_data_path: <PATH>
  #test_data_path: <PATH>
  
  n_train: 1000
  n_valid: 100

  batch_size: 32
  valid_batch_size: 100

  energy_regularisation: 1.0
  shuffle_buffer_size: 1000

callbacks:
- name: csv

checkpoints:
  ckpt_interval: 1

model:
  n_basis: 7
  n_radial: 5
  nn: [512, 512]

  r_max: 6.0
  r_min: 0.5

  b_init: normal
  descriptor_dtype: fp32
  readout_dtype: fp32
  scale_shift_dtype: fp32

loss:
- loss_type: molecules
  name: energy
  weight: 1.0
- loss_type: molecules
  name: forces
  weight: 4.0

metrics:
- name: energy
  reductions:
  - mae
- name: forces
  reductions:
  - mae
  - mse

optimizer:
  opt_name: adam
  emb_lr: 0.03
  nn_lr: 0.03
  opt_kwargs: {}
  scale_lr: 0.001
  shift_lr: 0.05
  transition_begin: 0

progress_bar:
  disable_epoch_pbar: false
  disable_nl_pbar: false

maximize_l2_cache: true
