name: documentation

on:
  push:
  schedule:
    - cron: '14 3 * * 1'  # at 03:14 on Monday.

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Run Poetry Image
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.2.2

    - name: Install Sphinx Dependencies
      run: |
        poetry --version
        poetry install

    - name: Build documentation
      run: |
        cd docs
        poetry run sphinx-build -b html source build