
name: Linting

on:
  push:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - name: Black Check
        uses: psf/black@stable
        with:
          src: "./gmnn_jax"
          version: "22.10.0"

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install isort
        run: |
          pip install isort==5.10.1

      - name: run isort
        run: |
          isort --check-only --quiet gmnn_jax

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install flake8
        run: |
          pip install flake8==5.0.4

      - name: run flake8
        run: |
          flake8 gmnn_jax --count --show-source --statistics
